baseurl = "https://jarzamendia.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Airsoft MS"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Airsoft MS"
  description = "Página para distribuição de missões!"
  avatar = "/me/jar.jpg"
  motto = "Si vis pacem, para bellum"
  
  email = "jearzamendia@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
