baseurl = "https://jarzamendia.github.io/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Airsoft MS"
theme = "hugo-theme-dream"
disablePathToLower = true
summaryLength = 20
enableSearch = true

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Airsoft MS"
  description = "Esta página foi criada para a distribuição de missões! Use por sua conta e risco."
  avatar = "/me/jar.jpg"
  motto = "Esta página foi criada para a distribuição de missões! Use por sua conta e risco."
  email = "jearzamendia@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 1960

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
